image: python:3.11

pipelines:
  default:
    - step: &lint
        name: Lint
        caches:
          - pip
        script:
          - pip install -r requirements_linting.txt
          - python project.py lint
    
    - step: &type
        name: Type
        caches:
          - pip
        script:
          - pip install -r requirements_typing.txt
          - python project.py type
    
    - step: &test
        name: Test
        caches:
          - pip
        script:
          - pip install -r requirements.txt
          - pip install -r requirements_testing.txt
          - python project.py test
  
  branches:
    deploy:
      - step: *lint
      - step: *type
      - step: *test
      - step:
          name: Build
          services:
            - docker
          script:
            - docker build -t joehitchen/fantasy-bumps .
            - docker save --output fantasy-bumps.docker joehitchen/fantasy-bumps
          artifacts:
            - fantasy-bumps.docker
      
      - step:
          name: Verify
          services:
            - docker
          script:
            - docker load --input fantasy-bumps.docker
            - docker run --rm joehitchen/fantasy-bumps python project.py test
      
      - step:
          name: Publish
          deployment: Docker
          services:
            - docker
          script:
            - docker load --input fantasy-bumps.docker
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - docker push joehitchen/fantasy-bumps

