# Generated by Django 2.1.5 on 2019-03-06 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('external', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='external.Seat')),
            ],
        ),
    ]
