# Generated by Django 2.2 on 2019-04-22 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('external', '0002_crew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['event', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mens_divisions', models.PositiveSmallIntegerField()),
                ('womens_divisions', models.PositiveSmallIntegerField()),
                ('boats_per_division', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='external.Crew')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FantasyBumps.Day')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='external.Seat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='external.Crew')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='FantasyBumps.Day')),
            ],
            options={
                'ordering': ['day', 'rank'],
            },
        ),
        migrations.AddField(
            model_name='day',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FantasyBumps.Event'),
        ),
    ]
