# Generated by Django 2.2 on 2019-06-23 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', "Men's"), ('W', "Women's")], db_index=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tag', models.SlugField(max_length=15, unique=True)),
                ('mens_divisions', models.PositiveSmallIntegerField()),
                ('womens_divisions', models.PositiveSmallIntegerField()),
                ('boats_per_division', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('cox', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('first_race_time', models.TimeField(db_index=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='FantasyBumps.Event')),
            ],
            options={
                'ordering': ['event', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FantasyBumps.Crew')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FantasyBumps.Day')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FantasyBumps.Seat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='FantasyBumps.Team')),
            ],
            options={
                'unique_together': {('team', 'day', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(db_index=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FantasyBumps.Crew')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='FantasyBumps.Day')),
            ],
            options={
                'ordering': ['day', 'rank'],
                'unique_together': {('day', 'crew')},
            },
        ),
    ]
