# Generated by Django 2.2 on 2019-07-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mens_budget', models.PositiveSmallIntegerField(default=1000)),
                ('womens_budget', models.PositiveSmallIntegerField(default=1000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasies', to='FantasyBumps.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='FantasyBumps.Team')),
            ],
            options={
                'unique_together': {('team', 'event')},
            },
        ),
    ]
