# Generated by Django 2.2 on 2019-05-16 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FantasyBumps', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('day', 'crew')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('team', 'day', 'seat')},
        ),
    ]
