# Generated by Django 2.2 on 2019-06-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='rank',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
