# Generated by Django 2.2 on 2019-11-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crew_lists', to='FantasyBumps.Crew')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crew_lists', to='FantasyBumps.Event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FantasyBumps.Seat')),
            ],
            options={
                'ordering': ['event', 'crew', 'seat'],
                'unique_together': {('event', 'crew', 'seat')},
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='FantasyBumps.Athlete'),
        ),
    ]
