# Generated by Django 2.2 on 2019-05-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='first_race_time',
            field=models.TimeField(db_index=True, null=True),
        ),
    ]
