# Generated by Django 2.2 on 2019-07-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0002_gameentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='mens_balance',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='gameentry',
            name='womens_balance',
            field=models.PositiveSmallIntegerField(default=1000),
        ),
    ]
