# Generated by Django 2.2 on 2019-11-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0002_athletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='FantasyBumps.Athlete'),
        ),
    ]
