# Generated by Django 2.2 on 2019-06-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0002_position_rank_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='gender',
            field=models.CharField(choices=[('M', "Men's"), ('W', "Women's")], db_index=True, max_length=1),
        ),
    ]
