# Generated by Django 2.2 on 2019-08-02 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0003_balances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='FantasyBumps.Crew'),
        ),
    ]
