# Generated by Django 2.2 on 2019-06-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0003_crew_gender_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='FantasyBumps.Event'),
        ),
    ]
