# Generated by Django 2.2 on 2019-06-22 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0004_event_days_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
