# Generated by Django 2.2 on 2019-08-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0004_auto_20190802_1228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
    ]
