# Generated by Django 2.2 on 2019-06-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0005_user_purchases_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='FantasyBumps.Day'),
        ),
    ]
