# Generated by Django 2.2 on 2019-08-12 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0005_remove_purchase_uniqueness_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='FantasyBumps.Day'),
        ),
    ]
