# Generated by Django 2.2 on 2019-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0006_day_purchase_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
