# Generated by Django 2.2 on 2019-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FantasyBumps', '0007_crew_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='name',
        ),
        migrations.AddField(
            model_name='crew',
            name='club',
            field=models.CharField(choices=[('ball', 'Balliol'), ('bras', 'Brasenose'), ('chri', 'Christ Church'), ('corp', 'Corpus Christi'), ('exet', 'Exeter'), ('grte', 'Green Templeton'), ('hert', 'Hertford'), ('jesu', 'Jesus'), ('kebl', 'Keble'), ('lady', 'Lady Margaret Hall'), ('lina', 'Linacre'), ('linc', 'Lincoln'), ('magd', 'Magdalen'), ('mans', 'Mansfield'), ('mert', 'Merton'), ('newc', 'New College'), ('orie', 'Oriel'), ('osle', 'Osler House'), ('pemb', 'Pembroke'), ('quee', "Queen's"), ('rege', "Regent's Park"), ('some', 'Somerville'), ('sann', "St Anne's"), ('sant', "St Antony's"), ('sben', "St Benet's"), ('scat', "St Catherine's"), ('sedm', 'St Edmund Hall'), ('shil', "St Hilda's"), ('shug', "St Hugh's"), ('sjoh', "St John's"), ('spet', "St Peter's"), ('trin', 'Trinity'), ('univ', 'University'), ('wadh', 'Wadham'), ('wolf', 'Wolfson'), ('worc', 'Worcester')], db_index=True, default='newc', max_length=4),
            preserve_default=False,
        ),
    ]
