# Generated by Django 2.2 on 2019-08-19 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('ball', 'Balliol'), ('bras', 'Brasenose'), ('chri', 'Christ Church'), ('corp', 'Corpus Christi'), ('exet', 'Exeter'), ('grte', 'Green Templeton'), ('hert', 'Hertford'), ('jesu', 'Jesus'), ('kebl', 'Keble'), ('lady', 'Lady Margaret Hall'), ('lina', 'Linacre'), ('linc', 'Lincoln'), ('magd', 'Magdalen'), ('mans', 'Mansfield'), ('mert', 'Merton'), ('newc', 'New College'), ('orie', 'Oriel'), ('osle', 'Osler House'), ('pemb', 'Pembroke'), ('quee', "Queen's"), ('rege', "Regent's Park"), ('some', 'Somerville'), ('sann', "St Anne's"), ('sant', "St Antony's"), ('sben', "St Benet's"), ('scat', "St Catherine's"), ('sedm', 'St Edmund Hall'), ('shil', "St Hilda's"), ('shug', "St Hugh's"), ('sjoh', "St John's"), ('spet', "St Peter's"), ('trin', 'Trinity'), ('univ', 'University'), ('wadh', 'Wadham'), ('wolf', 'Wolfson'), ('worc', 'Worcester')], db_index=True, max_length=4)),
                ('gender', models.CharField(choices=[('M', "Men's"), ('W', "Women's")], db_index=True, max_length=1)),
                ('rank', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('first_race_time', models.TimeField(db_index=True, null=True)),
            ],
            options={
                'ordering': ['event', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tag', models.SlugField(max_length=15, unique=True)),
                ('mens_divisions', models.PositiveSmallIntegerField()),
                ('womens_divisions', models.PositiveSmallIntegerField()),
                ('boats_per_division', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('cox', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fantasy.Crew')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='fantasy.Day')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fantasy.Seat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='fantasy.Team')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='fantasy.Event'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(db_index=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='fantasy.Crew')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='fantasy.Day')),
            ],
            options={
                'ordering': ['day', 'rank'],
                'unique_together': {('day', 'crew')},
            },
        ),
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mens_budget', models.PositiveSmallIntegerField(default=1000)),
                ('womens_budget', models.PositiveSmallIntegerField(default=1000)),
                ('mens_balance', models.PositiveSmallIntegerField(default=1000)),
                ('womens_balance', models.PositiveSmallIntegerField(default=1000)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasies', to='fantasy.Event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fantasy.Team')),
            ],
            options={
                'unique_together': {('team', 'event')},
            },
        ),
    ]
