# Generated by Django 2.2 on 2020-02-14 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_event_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='fantasy.Crew'),
        ),
    ]
