# Generated by Django 3.2 on 2021-04-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_crew_purchases_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women')], db_index=True, max_length=1),
        ),
    ]
