# Generated by Django 3.2 on 2021-04-18 09:52

from django.db import migrations, models
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor as SchemaEditor


def fill_womens_divisions_sizes(apps: Apps, schema_editor: SchemaEditor) -> None:
    Event = apps.get_model('fantasy', 'Event')
    Event.objects.update(womens_divisions_size = models.F('mens_divisions_size'))


def empty_womens_division_sizes(apps: Apps, schema_editor: SchemaEditor) -> None:
    Event = apps.get_model('fantasy', 'Event')
    Event.objects.update(womens_divisions_size = 0)


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_alter_crew_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='mens_divisions',
            new_name='mens_divisions_count',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='womens_divisions',
            new_name='womens_divisions_count',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='boats_per_division',
            new_name='mens_divisions_size',
        ),
        migrations.AddField(
            model_name='event',
            name='womens_divisions_size',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            fill_womens_divisions_sizes,
            empty_womens_division_sizes,
        )
    ]
