# Generated by Django 3.2 on 2021-05-26 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_division_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='fantasy.athlete'),
        ),
    ]
