# Generated by Django 3.2.13 on 2022-05-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_purchase_athlete_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mens_division_sizes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='womens_division_sizes',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='event',
            name='mens_divisions_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mens_divisions_size',
        ),
        migrations.RemoveField(
            model_name='event',
            name='womens_divisions_count',
        ),
        migrations.RemoveField(
            model_name='event',
            name='womens_divisions_size',
        ),
    ]
