# Generated by Django 3.2.13 on 2022-06-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0008_variable_division_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='club',
            field=models.CharField(choices=[('ball', 'Balliol'), ('bras', 'Brasenose'), ('chri', 'Christ Church'), ('corp', 'Corpus Christi'), ('exet', 'Exeter'), ('grte', 'Green Templeton'), ('hert', 'Hertford'), ('jesu', 'Jesus'), ('kebl', 'Keble'), ('lady', 'Lady Margaret Hall'), ('lina', 'Linacre'), ('linc', 'Lincoln'), ('magd', 'Magdalen'), ('mans', 'Mansfield'), ('mert', 'Merton'), ('newc', 'New College'), ('orie', 'Oriel'), ('osle', 'Osler House'), ('pemb', 'Pembroke'), ('quee', "Queen's"), ('rege', "Regent's Park"), ('some', 'Somerville'), ('sann', "St Anne's"), ('sant', "St Antony's"), ('sben', "St Benet's"), ('scat', "St Catherine's"), ('sedm', 'St Edmund Hall'), ('shil', "St Hilda's"), ('shug', "St Hugh's"), ('sjoh', "St John's"), ('spet', "St Peter's"), ('trin', 'Trinity'), ('univ', 'University'), ('wadh', 'Wadham'), ('wolf', 'Wolfson'), ('worc', 'Worcester'), ('adde', 'Addenbrookes'), ('angl', 'Anglia Ruskin'), ('caiu', 'Cauis'), ('chrc', "Christ's"), ('chur', 'Churchill'), ('clar', 'Clare'), ('clah', 'Clare Hall'), ('cocc', 'Corpus Christi'), ('darw', 'Darwin'), ('down', 'Downing'), ('emma', 'Emmanuel'), ('fatt', 'First & Third'), ('fitz', 'Fitzwilliam'), ('girt', 'Girton'), ('home', 'Homerton'), ('hugh', 'Hughes Hall'), ('jesc', 'Jesus'), ('king', "King's"), ('ladc', 'Lady Margaret'), ('lucy', 'Lucy Cavendish'), ('magc', 'Magdalene'), ('murr', 'Murray Edwards'), ('newn', 'Newnham'), ('pemc', 'Pembroke'), ('pete', 'Peterhouse'), ('quec', "Queens'"), ('robi', 'Robinson'), ('scac', "St Catherine's"), ('sedc', "St Edmund's"), ('selw', 'Selwyn'), ('sidn', 'Sidney Sussex'), ('trih', 'Trinity Hall'), ('wolc', 'Wolfson')], db_index=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='series',
            field=models.CharField(choices=[('D', 'Demo'), ('T', 'Torpids'), ('E', 'Eights'), ('L', 'Lents'), ('M', 'Mays')], db_index=True, max_length=1),
        ),
    ]
