# Generated by Django 3.2.18 on 2023-02-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0010_alter_caius_spelling'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='market_held_closed',
            field=models.BooleanField(default=False),
        ),
    ]
