# Generated by Django 3.2.18 on 2023-03-11 17:35

from django.db import migrations, models
from django.utils import timezone
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor as SchemaEditor

def flag_past_day_advanced(apps: Apps, schema_editor: SchemaEditor) -> None:
    (
        apps.get_model('fantasy', 'Day').objects
        .filter(date__lt = timezone.now().date(), first_race_time__isnull = False)
        .update(advanced = True)
    )


def noop(apps: Apps, schema_editor: SchemaEditor) -> None:
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_event_market_held_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='advanced',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(flag_past_day_advanced, noop),
    ]
