# Generated by Django 4.2 on 2023-06-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0012_day_advanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='last_race_time',
            field=models.TimeField(db_index=True, null=True),
        ),
    ]
