# Generated by Django 4.2 on 2023-06-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_add_vets_school'),
        ('fantasy', '0013_day_last_race_time'),
    ]

    operations = [
    ]
