# Generated by Django 4.2.19 on 2025-02-28 21:24

from django.db import migrations, models
from django.apps.registry import Apps
from django.db.backends.base.schema import BaseDatabaseSchemaEditor as SchemaEditor

from fantasy.constants import Series
from fantasy.management.trophies import assign_new_veterans


def add_veteran_status(apps: Apps, schema_editor: SchemaEditor) -> None:
    """Adds veteran status to all applicableteams."""

    Event = apps.get_model('fantasy', 'Event')

    latest_oxford_event = Event.objects.filter(series__in = [Series.TORPIDS, Series.EIGHTS]).last()
    if latest_oxford_event:
        assign_new_veterans(latest_oxford_event)

    latest_cambridge_event = Event.objects.filter(series__in = [Series.MAYS, Series.LENTS]).last()
    if latest_cambridge_event:
        assign_new_veterans(latest_cambridge_event)


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0016_event_initial_market_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='oxford_veteran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='cambridge_veteran',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            code = add_veteran_status,
            reverse_code = migrations.RunPython.noop,
        ),
    ]
