# Generated by Django 4.2.19 on 2025-03-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0017_veteran_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=9)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='fantasy.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophies', to='fantasy.team')),
            ],
            options={
                'ordering': ['type', '-event'],
            },
        ),
    ]
