# Generated by Django 4.2.19 on 2025-03-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0018_event_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='top_five_finisher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='top_ten_finisher',
            field=models.BooleanField(default=False),
        ),
    ]
