# Generated by Django 4.2.19 on 2025-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0020_alter_trophy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='has_subs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='type',
            field=models.CharField(choices=[('01-GOLDEN', 'Golden Swan'), ('02-SILVER', 'Silver Swan'), ('03-BRONZE', 'Bronze Swan'), ('04-G-COB', 'Golden Cob'), ('05-G-PEN', 'Golden Pen'), ('06-G-CYG', 'Golden Cygnet'), ('07-STEADY', 'Steady Swan')], max_length=9),
        ),
    ]
