# Generated by Django 4.2.19 on 2025-05-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0021_steady_swan_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='valid_entry',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='trophy',
            name='type',
            field=models.CharField(choices=[('01-GOLDEN', 'Golden Swan'), ('02-SILVER', 'Silver Swan'), ('03-BRONZE', 'Bronze Swan'), ('04-G-COB', 'Golden Cob'), ('05-G-PEN', 'Golden Pen'), ('06-G-CYG', 'Golden Cygnet'), ('07-STEADY', 'Steady Swan'), ('08-UGLY', 'Ugly Duckling')], max_length=9),
        ),
    ]
