# Generated by Django 4.2.19 on 2025-05-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0022_ugly_duckling_trophy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trophy',
            name='type',
            field=models.CharField(choices=[('01-GOLDEN', 'Golden Swan'), ('02-SILVER', 'Silver Swan'), ('03-BRONZE', 'Bronze Swan'), ('04-G-COB', 'Golden Cob'), ('05-G-PEN', 'Golden Pen'), ('06-G-CYG', 'Golden Cygnet'), ('07-STEADY', 'Steady Swan'), ('08-UGLY', 'Ugly Duckling'), ('09-JESTER', 'Jester Swan')], max_length=9),
        ),
    ]
