# Generated by Django 4.2.19 on 2026-03-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0023_jester_swan_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='mens_coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mens_coaching_entries', to='fantasy.crew'),
        ),
        migrations.AddField(
            model_name='gameentry',
            name='womens_coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='womens_coaching_entries', to='fantasy.crew'),
        ),
    ]
