# Generated by Django 4.2.30 on 2026-05-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0024_gameentry_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coaching_competition',
            field=models.CharField(choices=[('blades', 'Blades-or-Bust'), ('refund', 'Coaching Refund')], max_length=10, null=True),
        ),
    ]
