# Generated by Django 4.2.30 on 2026-05-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0025_event_coaching_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='fantasy.crew')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to='fantasy.event')),
            ],
            options={
                'ordering': ['event', 'crew'],
                'unique_together': {('event', 'crew')},
            },
        ),
    ]
