# Generated by Django 4.2.30 on 2026-07-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0026_coaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coaching_competition',
            field=models.CharField(choices=[('blades', 'Blades or Bust'), ('refund', 'Coaching Refund')], max_length=10, null=True),
        ),
    ]
