# Generated by Django 2.1.7 on 2019-04-06 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date', models.DateField(db_index=True)),
            ],
            options={
                'ordering': ['event', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mens_divisions', models.PositiveSmallIntegerField()),
                ('womens_divisions', models.PositiveSmallIntegerField()),
                ('boats_per_division', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bumps.Event'),
        ),
    ]
