# Generated by Django 2.1.7 on 2019-04-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external', '0002_crew'),
        ('Bumps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='external.Crew')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='Bumps.Day')),
            ],
            options={
                'ordering': ['day', 'rank'],
            },
        ),
    ]
