name: Quality Control

on:
  workflow_call:

jobs:
  qa:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Markdown Linting
            group: markdown
            sync-args: --only-group markdown
            command: markdown

          - name: Code Linting
            group: linting
            sync-args: --only-group linting
            command: lint

          - name: Typing
            group: typing
            sync-args: --only-group typing
            command: type

          - name: Testing
            group: testing
            sync-args: --group testing  # `--group ___` also includes base dependencies
            command: test

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.14'

      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true
          cache-suffix: ${{ matrix.group }}

      - name: Install dependencies
        run: uv sync ${{ matrix.sync-args }}

      - name: Run checks
        run: python project.py ${{ matrix.command }}
